// This file was autogenerated by print_selective_registration_header.py
#ifndef OPS_TO_REGISTER
#define OPS_TO_REGISTER

    namespace {
      constexpr const char* skip(const char* x) {
        return (*x) ? (*x == ' ' ? skip(x + 1) : x) : x;
      }

      constexpr bool isequal(const char* x, const char* y) {
        return (*skip(x) && *skip(y))
                   ? (*skip(x) == *skip(y) && isequal(skip(x) + 1, skip(y) + 1))
                   : (!*skip(x) && !*skip(y));
      }

      template<int N>
      struct find_in {
        static constexpr bool f(const char* x, const char* const y[N]) {
          return isequal(x, y[0]) || find_in<N - 1>::f(x, y + 1);
        }
      };

      template<>
      struct find_in<0> {
        static constexpr bool f(const char* x, const char* const y[]) {
          return false;
        }
      };
    }  // end namespace
    constexpr const char* kNecessaryOpKernelClasses[] = {
"BinaryOp<CPUDevice, functor::add<float>>",
"BiasOp<CPUDevice, float>",
"ConcatV2Op<CPUDevice, float>",
"ConstantOp",
"FillOp<CPUDevice, float, int32>",
"GatherOp<CPUDevice, float, int32>",
"IdentityOp",
"MatMulOp<CPUDevice, float, false >",
"BinaryOp<CPUDevice, functor::mul<float>>",
"NoOp",
"PackOp<CPUDevice, float>",
"PlaceholderOp",
"IdentityOp",
"ReshapeOp",
"UnaryOp<CPUDevice, functor::sigmoid<float>>",
"SoftmaxOp<CPUDevice, float>",
"SplitOpCPU<float>",
"StridedSliceOp<CPUDevice, float>",
"UnaryOp<CPUDevice, functor::tanh<float>>",
"TopK<CPUDevice, float>",
"UnpackOp<CPUDevice, float>",
"RecvOp",
"SendOp",
};
#define SHOULD_REGISTER_OP_KERNEL(clz) (find_in<sizeof(kNecessaryOpKernelClasses) / sizeof(*kNecessaryOpKernelClasses)>::f(clz, kNecessaryOpKernelClasses))

constexpr inline bool ShouldRegisterOp(const char op[]) {
  return false
     || isequal(op, "Add")
     || isequal(op, "BiasAdd")
     || isequal(op, "ConcatV2")
     || isequal(op, "Const")
     || isequal(op, "Fill")
     || isequal(op, "GatherV2")
     || isequal(op, "Identity")
     || isequal(op, "MatMul")
     || isequal(op, "Mul")
     || isequal(op, "NoOp")
     || isequal(op, "Pack")
     || isequal(op, "Placeholder")
     || isequal(op, "PlaceholderWithDefault")
     || isequal(op, "Reshape")
     || isequal(op, "Sigmoid")
     || isequal(op, "Softmax")
     || isequal(op, "Split")
     || isequal(op, "StridedSlice")
     || isequal(op, "Tanh")
     || isequal(op, "TopKV2")
     || isequal(op, "Unpack")
     || isequal(op, "_Recv")
     || isequal(op, "_Send")
  ;
}
#define SHOULD_REGISTER_OP(op) ShouldRegisterOp(op)

#define SHOULD_REGISTER_OP_GRADIENT false
#endif
